"""Build the A4 speaker script: one page per slide, slide image on top, script below.

Source: docs/speech_script.md (sections "## N · Title | Speaker | duration | clock" with SAY/NUMBERS/TERMS/NEXT).
Slide images: slides/main.pdf (page N).
Output: slides/speaker_script.tex  ->  cd slides && latexmk -pdf speaker_script.tex

Usage (repo root): python code/make_speaker_script.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC, OUT = ROOT / 'docs' / 'speech_script.md', ROOT / 'slides' / 'speaker_script.tex'
COLOR = {'Zheng': 'navy', 'Diego': 'nlred', 'both': 'grey'}
FIELDS = ('SAY', 'NUMBERS', 'TERMS', 'NEXT')

PREAMBLE = r"""% Generated by code/make_speaker_script.py from docs/speech_script.md -- edit the Markdown, not this file.
\documentclass[10pt]{article}
\usepackage[a4paper,margin=1.2cm,top=1.0cm,bottom=1.0cm]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{newpxtext,newpxmath}
\usepackage{graphicx,xcolor,newunicodechar,pifont,enumitem}
\usepackage[most]{tcolorbox}
\tcbuselibrary{fitting}
\definecolor{navy}{HTML}{1F3B73}\definecolor{nlred}{HTML}{A93226}\definecolor{grey}{HTML}{7F8C8D}
\definecolor{gold}{HTML}{E0A100}\definecolor{okgreen}{HTML}{2E8B57}
\newunicodechar{−}{\textminus}\newunicodechar{→}{\ensuremath{\rightarrow}}\newunicodechar{≈}{\ensuremath{\approx}}
\newunicodechar{≤}{\ensuremath{\leq}}\newunicodechar{↑}{\ensuremath{\uparrow}}\newunicodechar{€}{\texteuro}
\newunicodechar{λ}{\ensuremath{\lambda}}\newunicodechar{…}{\ldots}\newunicodechar{×}{\ensuremath{\times}}
\setlist[itemize]{leftmargin=1.1em,itemsep=1.5pt,topsep=1pt,parsep=0pt}
\setlist[itemize,2]{leftmargin=1.0em,itemsep=0.5pt,label=--}
\pagestyle{empty}\setlength{\parindent}{0pt}
\tcbset{sbox/.style={enhanced,fit,fit fontsize macros,fit algorithm=fontsize,colback=white,boxrule=0.5pt,arc=2pt,
  left=5pt,right=5pt,top=3pt,bottom=3pt,fonttitle=\bfseries\small,toptitle=1pt,bottomtitle=1pt,before upper=\raggedright}}
\begin{document}
"""


def esc(t):
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'), ('$', r'\$'), ('#', r'\#'), ('_', r'\_'),
                 ('{', r'\{'), ('}', r'\}'), ('~', r'\textasciitilde{}'), ('^', r'\textasciicircum{}')]:
        t = t.replace(a, b)
    return t


def inline(t):
    t = esc(t)
    t = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', t)
    t = re.sub(r'\*(.+?)\*', r'\\emph{\1}', t)
    return t.replace('HAND-OVER', r'\textcolor{nlred}{\textbf{HAND-OVER}}')


def items(lines, terms=False):
    """Markdown bullets (2-space indent = level 2) -> nested itemize."""
    out, level = [], 0
    for ln in lines:
        m = re.match(r'(\s*)- (.*)', ln)
        if not m:
            continue
        lvl = 1 + len(m.group(1)) // 2
        while level < lvl:
            out.append(r'\begin{itemize}'); level += 1
        while level > lvl:
            out.append(r'\end{itemize}'); level -= 1
        txt = m.group(2)
        if terms and ': ' in txt:
            term, defn = txt.split(': ', 1)
            txt_tex = r'\textbf{' + inline(term) + ':} ' + inline(defn)
        else:
            txt_tex = inline(txt)
        out.append(r'\item ' + txt_tex)
    out += [r'\end{itemize}'] * level
    return '\n'.join(out)


def page(head, body, total):
    num, title, who, dur, clock = [x.strip() for x in re.split(r'\s*[·|]\s*', head, maxsplit=4)]
    col = COLOR.get(who, 'grey')
    parts, cur = {f: [] for f in FIELDS}, None
    for ln in body.split('\n'):
        m = re.match(r'(SAY|NUMBERS|TERMS|NEXT):\s*(.*)', ln)
        if m:
            cur = m.group(1)
            if m.group(2):
                parts[cur].append(m.group(2))
        elif cur and ln.strip():
            parts[cur].append(ln)
    who_txt = {'Zheng': 'Zheng Huang', 'Diego': 'Diego Gutiérrez', 'both': 'Both speakers'}.get(who, who)
    timing = f'{dur} · from {clock}' if re.match(r'\d', dur) else f'{dur} · {clock}'
    return rf"""
\begin{{tcolorbox}}[enhanced,colback={col},colframe={col},arc=2pt,boxrule=0pt,left=6pt,right=6pt,top=3pt,bottom=3pt]
\color{{white}}\bfseries\large Page {esc(num)}/{total} · {inline(title)}\hfill\normalsize {esc(who_txt)} · {esc(timing)}
\end{{tcolorbox}}\par\vspace{{1pt}}
\fcolorbox{{black!25}}{{white}}{{\includegraphics[page={num},width=\dimexpr\linewidth-2\fboxsep-2\fboxrule\relax]{{main.pdf}}}}\par\vspace{{4pt}}
\begin{{tcolorbox}}[sbox,width=0.585\linewidth,height=13.2cm,nobeforeafter,box align=top,fit basedim=13pt,colframe={col},colbacktitle={col}!12,coltitle={col},title=SAY]
{items(parts['SAY'])}
\end{{tcolorbox}}\hfill
\begin{{minipage}}[t]{{0.405\linewidth}}\vspace{{0pt}}
\begin{{tcolorbox}}[sbox,height=6.45cm,fit basedim=11.5pt,colframe=black!35,colbacktitle=black!6,coltitle=black,title=NUMBERS]
{items(parts['NUMBERS'])}
\end{{tcolorbox}}\par\vspace{{0.3cm}}
\begin{{tcolorbox}}[sbox,height=6.45cm,fit basedim=11.5pt,colframe=black!35,colbacktitle=black!6,coltitle=black,title=TERMS EXPLAINED]
{items(parts['TERMS'], terms=True)}
\end{{tcolorbox}}
\end{{minipage}}\par\vspace{{4pt}}
\begin{{tcolorbox}}[enhanced,colback={col}!6,colframe={col}!50,boxrule=0.5pt,arc=2pt,left=6pt,right=6pt,top=3pt,bottom=3pt]
\small\textbf{{\color{{{col}}}NEXT →}}\ {inline(' '.join(parts['NEXT']))}
\end{{tcolorbox}}
\newpage
"""


def main():
    text = SRC.read_text().split('\n---\n', 1)[1]
    secs = [s for s in re.split(r'\n## ', '\n' + text)[1:]]
    pages = []
    for sec in secs:
        head, body = sec.split('\n', 1)
        pages.append((head, body))
    total = len(pages)
    OUT.write_text(PREAMBLE + ''.join(page(h, b, total) for h, b in pages) + '\\end{document}\n')
    print(f'{total} pages -> {OUT}')


if __name__ == '__main__':
    main()
