"""Build the A4 speaker script: one page per slide, slide image on top, script below.

Source: docs/speech_script.md (sections "## N · Title | duration" with STORY and LIKELY CHALLENGES).
Slide images: slides/main.pdf (page N).
Output: slides/speaker_script.tex  ->  cd slides && latexmk -pdf speaker_script.tex

Usage (repo root): python code/make_speaker_script.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC, OUT = ROOT / 'docs' / 'speech_script.md', ROOT / 'slides' / 'speaker_script.tex'
FIELDS = ('STORY', 'LIKELY CHALLENGES')

PREAMBLE = r"""% Generated by code/make_speaker_script.py from docs/speech_script.md -- edit the Markdown, not this file.
\documentclass[10pt]{article}
\usepackage[a4paper,margin=1.2cm,top=1.0cm,bottom=1.0cm]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{newpxtext,newpxmath}
\usepackage{graphicx,xcolor,newunicodechar,pifont,enumitem}
\usepackage[most]{tcolorbox}
\tcbuselibrary{fitting}
\definecolor{navy}{HTML}{1F3B73}\definecolor{nlred}{HTML}{A93226}\definecolor{grey}{HTML}{7F8C8D}
\definecolor{gold}{HTML}{E0A100}\definecolor{okgreen}{HTML}{2E8B57}
\newunicodechar{−}{\textminus}\newunicodechar{→}{\ensuremath{\rightarrow}}\newunicodechar{≈}{\ensuremath{\approx}}
\newunicodechar{≤}{\ensuremath{\leq}}\newunicodechar{↑}{\ensuremath{\uparrow}}\newunicodechar{€}{\texteuro}
\newunicodechar{λ}{\ensuremath{\lambda}}\newunicodechar{⁴}{\textsuperscript{4}}\newunicodechar{…}{\ldots}\newunicodechar{×}{\ensuremath{\times}}
\setlist[itemize]{leftmargin=1.1em,itemsep=1.5pt,topsep=1pt,parsep=0pt}
\setlist[itemize,2]{leftmargin=1.0em,itemsep=0.5pt,label=--}
\pagestyle{empty}\setlength{\parindent}{0pt}
\tcbset{sbox/.style={enhanced,fit,fit fontsize macros,fit algorithm=fontsize,colback=white,boxrule=0.5pt,arc=2pt,
  left=5pt,right=5pt,top=3pt,bottom=3pt,fonttitle=\bfseries\small,toptitle=1pt,bottomtitle=1pt,before upper=\raggedright}}
\begin{document}
"""


def esc(t):
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'), ('$', r'\$'), ('#', r'\#'), ('_', r'\_'),
                 ('{', r'\{'), ('}', r'\}'), ('~', r'\textasciitilde{}'), ('^', r'\textasciicircum{}')]:
        t = t.replace(a, b)
    return t


def inline(t):
    t = esc(t)
    t = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', t)
    t = re.sub(r'\*(.+?)\*', r'\\emph{\1}', t)
    return t


def items(lines, qa=False):
    """Markdown bullets (2-space indent = level 2) -> nested itemize. qa=True renders 'Q: ...' as a bold question."""
    out, level = [], 0
    for ln in lines:
        m = re.match(r'(\s*)- (.*)', ln)
        if not m:
            continue
        lvl = 1 + len(m.group(1)) // 2
        while level < lvl:
            out.append(r'\begin{itemize}'); level += 1
        while level > lvl:
            out.append(r'\end{itemize}'); level -= 1
        txt = m.group(2)
        if qa and txt.startswith('Q: '):
            out.append(r'\item[\textcolor{navy}{\textbf{Q}}] \textbf{' + inline(txt[3:]) + '}')
        else:
            out.append(r'\item ' + inline(txt))
    out += [r'\end{itemize}'] * level
    return '\n'.join(out)


def page(head, body, total):
    num, rest = [x.strip() for x in head.split('·', 1)]
    title, dur = [x.strip() for x in rest.split('|', 1)]
    parts, cur = {f: [] for f in FIELDS}, None
    for ln in body.split('\n'):
        m = re.match(r'(STORY|LIKELY CHALLENGES):\s*(.*)', ln)
        if m:
            cur = m.group(1)
            if m.group(2):
                parts[cur].append(m.group(2))
        elif cur and ln.strip():
            parts[cur].append(ln)
    timing = f'about {dur}' if re.match(r'\d', dur) else 'backup for questions'
    return rf"""
\begin{{tcolorbox}}[enhanced,colback=navy,colframe=navy,arc=2pt,boxrule=0pt,left=6pt,right=6pt,top=3pt,bottom=3pt]
\color{{white}}\bfseries\large Page {esc(num)}/{total} · {inline(title)}\hfill\normalsize {esc(timing)}
\end{{tcolorbox}}\par\vspace{{1pt}}
\fcolorbox{{black!25}}{{white}}{{\includegraphics[page={num},width=\dimexpr\linewidth-2\fboxsep-2\fboxrule\relax]{{main.pdf}}}}\par\vspace{{4pt}}
\begin{{tcolorbox}}[sbox,width=0.495\linewidth,height=14.6cm,nobeforeafter,box align=top,fit basedim=12.5pt,colframe=navy,colbacktitle=navy!10,coltitle=navy,title=STORY · what to say]
{items(parts['STORY'])}
\end{{tcolorbox}}\hfill
\begin{{tcolorbox}}[sbox,width=0.495\linewidth,height=14.6cm,nobeforeafter,box align=top,fit basedim=11pt,colframe=nlred!70,colbacktitle=nlred!8,coltitle=nlred,title=LIKELY CHALLENGES · definitions and logic]
{items(parts['LIKELY CHALLENGES'], qa=True)}
\end{{tcolorbox}}
\newpage
"""


def main():
    text = SRC.read_text().split('\n---\n', 1)[1]
    secs = [s for s in re.split(r'\n## ', '\n' + text)[1:]]
    pages = []
    for sec in secs:
        head, body = sec.split('\n', 1)
        pages.append((head, body))
    total = len(pages)
    OUT.write_text(PREAMBLE + ''.join(page(h, b, total) for h, b in pages) + '\\end{document}\n')
    print(f'{total} pages -> {OUT}')


if __name__ == '__main__':
    main()
