"""Build printable cue cards (4 per A4 page) from docs/cue_cards.md -> slides/cue_cards.tex.

Usage (repo root):  python code/make_cue_cards.py && (cd slides && latexmk -pdf cue_cards.tex)
"""
import re
from pathlib import Path

from make_notes import esc

ROOT = Path(__file__).resolve().parents[1]
SRC, OUT = ROOT / 'docs' / 'cue_cards.md', ROOT / 'slides' / 'cue_cards.tex'
COLOR = {'Zheng': 'navy', 'Diego': 'nlred', 'both': 'grey'}

PREAMBLE = r"""% Generated by code/make_cue_cards.py from docs/cue_cards.md -- edit the Markdown, not this file.
\documentclass[10pt]{article}
\usepackage[a4paper,landscape,margin=0.7cm]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[sfdefault]{FiraSans}
\usepackage{xcolor,newunicodechar,pifont,enumitem}
\usepackage[most]{tcolorbox}
\tcbuselibrary{fitting}
\definecolor{navy}{HTML}{1F3B73}\definecolor{nlred}{HTML}{C0392B}\definecolor{grey}{HTML}{7F8C8D}\definecolor{gold}{HTML}{E0A100}
\newunicodechar{−}{\textminus}\newunicodechar{→}{\ensuremath{\rightarrow}}\newunicodechar{≈}{\ensuremath{\approx}}
\newunicodechar{≤}{\ensuremath{\leq}}\newunicodechar{↑}{\ensuremath{\uparrow}}\newunicodechar{€}{\texteuro}
\newunicodechar{✔}{\textcolor{green!50!black}{\ding{51}}}\newunicodechar{★}{\textcolor{gold}{\ding{72}}}
\newunicodechar{…}{\ldots}
\setlist[itemize]{leftmargin=1.1em,itemsep=1pt,topsep=2pt,parsep=0pt,label=\textcolor{#1}{\textbullet}}
\pagestyle{empty}\setlength{\parindent}{0pt}
\newtcolorbox{card}[2]{enhanced,nobeforeafter,box align=top,width=0.492\linewidth,height=0.475\textheight,fit,fit fontsize macros,fit basedim=17pt,fit algorithm=fontsize,
  colframe=#1,colback=white,boxrule=0.6pt,arc=2pt,left=6pt,right=6pt,top=4pt,bottom=4pt,
  borderline={0.3pt}{-3.5pt}{black!35,dashed},
  title={#2},fonttitle=\bfseries\large,coltitle=white,colbacktitle=#1,toptitle=2pt,bottomtitle=2pt}
\begin{document}
"""


def inline(t):
    t = esc(t)
    t = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', t)
    t = re.sub(r'\*(.+?)\*', r'\\emph{\1}', t)
    t = t.replace('DEF:', r'\textcolor{gold!80!black}{\textbf{DEF}}')
    t = t.replace('HAND-OVER:', r'\textcolor{nlred}{\textbf{HAND-OVER:}}')
    return t


def card(head, lines):
    num, title, who, dur, clock = [x.strip() for x in re.split(r'\s*[·|]\s*', head, maxsplit=4)]
    col = COLOR.get(who, 'grey')
    title_tex = (rf'\makebox[0pt][l]{{{esc(num)} \quad {inline(title)}}}\hfill'
                 rf'{{\normalsize\mdseries {esc(who)} · {esc(dur)} · from {esc(clock)}}}')
    body, items = [], []

    def flush():
        if items:
            body.append(r'\begin{itemize}[label=\textcolor{' + col + r'}{\textbullet}]' + ''.join(r'\item ' + i for i in items) + r'\end{itemize}')
            items.clear()

    for ln in lines:
        ln = ln.rstrip()
        if not ln:
            continue
        if ln.startswith('OPEN:'):
            flush(); body.append(r'{\large\itshape ' + inline(ln[5:].strip()) + r'}\par\smallskip')
        elif ln.startswith('- '):
            items.append(inline(ln[2:]))
        elif ln.startswith('#:'):
            flush(); body.append(r'\smallskip{\color{' + col + r'}\textbf{\#}}\ ' + inline(ln[2:].strip()) + r'\par')
        elif ln.startswith('→'):
            flush(); body.append(r'\vfill\textcolor{grey}{\rule{\linewidth}{0.3pt}}\par{\bfseries\color{' + col + r'}→}\ ' + inline(ln[1:].strip()))
    flush()
    return r'\begin{card}{' + col + '}{' + title_tex + '}\n' + '\n'.join(body) + '\n\\end{card}'


def main():
    text = SRC.read_text().split('\n---\n', 1)[1]
    cards = []
    for sec in re.split(r'\n## ', '\n' + text)[1:]:
        head, *lines = sec.split('\n')
        cards.append(card(head, lines))
    out = [PREAMBLE]
    for i, c in enumerate(cards):
        out.append(c)
        out.append('\\hfill' if i % 2 == 0 else '\n\n\\vspace{0.35cm}\n' if i % 4 == 1 else '\n\\newpage\n')
    out.append('\\end{document}\n')
    OUT.write_text('\n'.join(out))
    print(f'{len(cards)} cards -> {OUT}')


if __name__ == '__main__':
    main()
